### ISSUE TITLE
ovirtsdk4 version 4.3.0 or higher is required for this module

### ISSUE THREAD

**Issue by jasonnykamp** [oVirt/ovirt-ansible-collection#244]
Having an issue with the sdk. I am running RHEL7, python2.7, ansible 2.9, and skd 4.3.4.

Any help would be appreciated.

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ovirt_auth_payload_2REfEd/ansible_ovirt_auth_payload.zip/ansible/modules/cloud/ovirt/ovirt_auth.py", line 204, in <module>
  File "/home/shared/python/ansible-29/lib/python2.7/site-packages/ovirtsdk4/__init__.py", line 22, in <module>
    import pycurl

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ca_file": "ca.pem", 
            "compress": true, 
            "headers": null, 
            "hostname": "rhevm", 
            "insecure": true, 
            "kerberos": false, 
            "ovirt_auth": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "timeout": 0, 
            "token": null, 
            "url": null, 
            "username": "admin@internal"
        }
    }, 
    "msg": "ovirtsdk4 version 4.3.0 or higher is required for this module"
}
```

**Comment by mnecas** [comment]
Hi @jasonnykamp
how did you install the sdk? Did you used pip or rpm?

**Comment by jasonnykamp** [comment]
I installed it with rpm

**Comment by mnecas** [comment]
Do you have installed pycurl?

**Comment by jasonnykamp** [comment]
pycurl is installed

**Comment by mnecas** [comment]
What do you get from python code?
```python
import ovirtsdk4.version as sdk_version
print(sdk_version.VERSION)
```

**Comment by jasonnykamp** [comment]
```
>>> import ovirtsdk4.version as sdk_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shared/python/ansible-29/lib/python2.7/site-packages/ovirtsdk4/__init__.py", line 22, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (nss) is different from compile-time ssl backend (none/other)
```

**Comment by mnecas** [comment]
First time seeing this issue, looks like on the specific env,
most tips which I found are to uninstall the pycurl set:
`export PYCURL_SSL_LIBRARY=openssl`
and install it once again

**Comment by jasonnykamp** [comment]
Unfortunately, I can't uninstall pycurl. It simply fails every time I try. Would it be possible to just set that export before running a play?

**Comment by mnecas** [comment]
It is worth a try but it goes outside of my knowledge scope
would recommend to check out https://stackoverflow.com/questions/21096436/ssl-backend-error-when-using-openssl
