### ISSUE TITLE
ovirt_nic_module: parameter nested_attributes failed

### ISSUE THREAD

**Issue by Gounick** [oVirt/ovirt-ansible-collection#450]
Hello,
Could you help me on this subject? The Ansible documentation is poor and there are no examples.

I am trying to set up MAC filtering with a vNIC profile with the clean-traffic-gateway filter.

The advantage is to place several VMs in the same subnet but to prevent them from talking to each other. The only authorized flow is the gateway.

It's OK with API and WebUI but cannot reproduce with nested_attributes parameter of Ansible module ovirt_nic

* https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_nic_module.html#parameter-nested_attributes

The vNIC profile is correctly configured on the clean-traffic-gateway filter.

```
    - name: "Add NIC to VM"
      ovirt.ovirt.ovirt_nic:
       auth: "{{ ovirt_auth }}"
       state: present
       vm: "{{ vm }}"
       name: "{{ nic_name }}"
       interface: virtio
       profile: "{{ profile }}"
       network: "{{ network }}"
       fetch_nested: true
       nested_attributes:
         - network_filter_parameters:
             - name: GATEWAY_MAC
               value: "00:00:00:00:00:01"
```

Error is:

```
TASK [Add adm NIC to my VM] *****************************************************************************************************************************************************************
task path: /home/*****/playbook_debug.yml:136
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt.ovirt.ovirt_nic_payload_bg25qz3t/ansible_ovirt.ovirt.ovirt_nic_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_nic.py", line 329, in main
  File "/tmp/ansible_ovirt.ovirt.ovirt_nic_payload_bg25qz3t/ansible_ovirt.ovirt.ovirt_nic_payload.zip/ansible_collections/ovirt/ovirt/plugins/module_utils/ovirt.py", line 672, in create
    entity = self._service.add(
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/services.py", line 36252, in add
    return self._internal_add(nic, headers, query, wait)
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/service.py", line 232, in _internal_add
    return future.wait() if wait else future
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/service.py", line 229, in callback
    self._check_fault(response)
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/service.py", line 132, in _check_fault
    self._raise_error(response, body)
  File "/home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Failed to activate VM Network Interface.]". HTTP response code is 400.
fatal: [rhevm-infra]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "fetch_nested": true,
            "id": null,
            "interface": "virtio",
            "linked": false,
            "mac_address": null,
            "name": "adm",
            "nested_attributes": [
                "{'network_filter_parameters': [{'name': 'GATEWAY_MAC', 'value': '00:00:00:00:00:01'}]}"
            ],
            "network": "adm",
            "poll_interval": 3,
            "profile": "adm",
            "state": "unplugged",
            "template": null,
            "template_version": null,
            "timeout": 180,
            "vm": "myvm",
            "wait": true
        }
    },
    "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Failed to activate VM Network Interface.]\". HTTP response code is 400."
}
```

## My versions are:

* oVirt Open Virtualization Manager - Version:4.4.2.6-1.el8

* ansible --version

```
ansible [core 2.12.2]
  config file = /home/*****/*****/*****/*****/ansible.cfg
  configured module search path = ['/home/*****/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/*****/.virtualenvs/*****/lib/python3.8/site-packages/ansible
  ansible collection location = /home/*****/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/*****/.virtualenvs/*****/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

* ansible-galaxy collection list

```
Collection             Version
---------------------- -------  
ansible.utils          2.5.2  
community.general      4.5.0  
ovirt.ovirt            1.6.5
ovirt.ovirt                   1.6.6
```

* pip list | grep -i ovirt

```
ovirt-engine-sdk-python           4.5.0
```

* lsb_release -ds

```
Ubuntu 20.04.4 LTS
```

Best regard

**Comment by Gounick** [comment]
Hello, I updated the main post.
