### ISSUE TITLE
ovirt_vm module: VM deployment fails "Error during SSO authentication access_denied"

### ISSUE THREAD

**Issue by rgreg51** [oVirt/ovirt-ansible-collection#575]
##### SUMMARY
Wondering whether someone could help. Not sure whether this is a bug. 

Create a user in keycloak, added it to oVirt via the admin portal and assigned the 'user role' "PowerUser".

Logging on as the user in the 'VM portal', I can successfully deploy a VM from template 'manually'. However using the ansible vm module I hit an error. (For reference: If I use a user with "SuperUser" role assigned it works perfectly).

##### COMPONENT NAME
ovirt_vm
##### STEPS TO REPRODUCE

```yaml
 ovirt.ovirt.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: Default    
    name: vm1
    template: tpl-rh8
    memory: 2G
    cpu_cores: 2
    cpu_sockets: 1
    type: server
    storage_domain: vmstore
    nics: 
      - name: nic1
        profile_name: vmnetwork
    state: running
    timeout: 300
    wait: yes
```

##### EXPECTED RESULTS
Deploy VM from template and power up

##### ACTUAL RESULTS

```paste below
"msg": "Error during SSO authentication access_denied : Cannot authenticate user No valid profile found in credentials.."
```
##### FULL TRACEBACK
```
Traceback (most recent call last):
  File "/tmp/ansible_ovirt.ovirt.ovirt_vm_info_payload_91dyu8x3/ansible_ovirt.ovirt.ovirt_vm_info_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm_info.py", line 160, in main
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/services.py", line 38746, in list
    return self._internal_get(headers, query, wait)
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/service.py", line 211, in _internal_get
    return future.wait() if wait else future
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/service.py", line 54, in wait
    response = self._connection.wait(self._context)
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/__init__.py", line 496, in wait
    return self.__wait(context, failed_auth)
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/__init__.py", line 526, in __wait
    self._sso_token = self._get_access_token()
  File "/home/user/autom-venv/lib64/python3.10/site-packages/ovirtsdk4/__init__.py", line 624, in _get_access_token
    raise AuthError(
ovirtsdk4.AuthError: Error during SSO authentication access_denied : Cannot authenticate user No valid profile found in credentials..
```

###### VERSIONS
oVirt: 4.5.1.3-1.el8

ansible
```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/autom-venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/autom-venv/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.1.2
  libyaml = True
```
ansible-galaxy collection
```
ovirt.ovirt                   2.0.4
```
pip list
```
ovirt-engine-sdk-python 4.5.1
```
python -V
```
Python 3.10.5
```
fedora 36

**Comment by michalskrivanek** [comment]
possibly a bug indeed. overall our API is not very well suited for non-admins. VM Portal have several workarounds as the primary user is supposed to be non-admin. But with ansible or raw API usage it may require admin privileges at surprising places

**Comment by mnecas** [comment]
Could you try some requests on the API? Something like:
`curl -k https://engine.com/ovirt-engine/api --user admin@ovirt@internalsso:password`
to just see if the API works correctly with the keycloak user

**Comment by rgreg51** [comment]
Hi @mnecas 

when I attempt: 
`curl -k https://my-ovirt-engine.mydomain/ovirt-engine/api --user admin@ovirt@internalsso:admin-password`
or with any other 'SuperUser or 'PowerUser'

I get:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

**Comment by mnecas** [comment]
Thanks for the quick reply! I got the same results just wanted to make sure that you have it also... This is not an ansible collection issue but in the API.

**Comment by michalskrivanek** [comment]
I believe keycloak-enabled setup drops basic auth. you need oauth bearer tokens - http://ovirt.github.io/ovirt-engine-api-model/master/#oauth-authentication

**Comment by mnecas** [comment]
@rgreg51 have you added the user suffix `@internalsso`? like `admin@ovirt@internalsso` or `user@internalsso`

**Comment by rgreg51** [comment]
@mnecas I have now tried all permutations for a user with a 'PowerUser' role assigned and none works.

For a user with 'SuperUser' role assigned:
`admin@internalsso` works
`admin@ovirt@internalsso` does NOT work
