### ISSUE TITLE
DR scripts fail to authenticate on failback

### ISSUE THREAD

**Issue by ahadas** [oVirt/ovirt-ansible-collection#615]
Stacktrace:

TASK [ovirt.ovirt.disaster_recovery : Fetch VMs in the storage domain] *******************************************************************************************************************************
task path: /usr/share/ansible/collections/ansible_collections/ovirt/ovirt/roles/disaster_recovery/tasks/clean/shutdown_vms.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436 `" && echo ansible-tmp-1667473739.7456415-94384-218874299046436="` echo /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436 `" ) && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm_info.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-94193lfxzx44q/tmprv9eo5oo TO /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436/AnsiballZ_ovirt_vm_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436/ /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436/AnsiballZ_ovirt_vm_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436/AnsiballZ_ovirt_vm_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1667473739.7456415-94384-218874299046436/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_vm_info_payload_qmsqesc6/ansible_ovirt_vm_info_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_vm_info.py", line 153, in main
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/services.py", line 38003, in list
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 211, in _internal_get
    return future.wait() if wait else future
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 54, in wait
    response = self._connection.wait(self._context)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/__init__.py", line 496, in wait
    return self.__wait(context, failed_auth)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/__init__.py", line 526, in __wait
    self._sso_token = self._get_access_token()
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/__init__.py", line 627, in _get_access_token
    sso_error[1]
ovirtsdk4.AuthError: Error during SSO authentication access_denied : Cannot authenticate user 'None@N/A': No valid profile found in credentials..
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "all_content": false,
            "case_sensitive": true,
            "current_cd": false,
            "fetch_nested": false,
            "follow": [],
            "max": null,
            "nested_attributes": [],
            "next_run": null,
            "pattern": "status != down and storage.name=Gluster_tom_slave and datacenter=Default\n"
        }
    },
    "msg": "Error during SSO authentication access_denied : Cannot authenticate user 'None@N/A': No valid profile found in credentials.."

Original bug: https://bugzilla.redhat.com/show_bug.cgi?id=2139783

**Comment by pikodd** [comment]
Hi!
I have same issue. Have you fixed it?
