### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data_center'

### ISSUE THREAD

**Issue by zionly** [oVirt/ovirt-ansible-collection#617]
##### STEPS TO REPRODUCE

With `ovirt_vm`, specify an invalid cluster name like this :

```yaml

- name: Create VMs
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "INVALID_CLUSTER_NAME"
       [...]
```

##### ACTUAL RESULTS

You will have the following error : 

```
The full traceback is:
Traceback (most recent call last):
  File "x/ansible/modules/cloud/ovirt/ovirt_vm.py", line 2477, in main
  File "x/ansible/module_utils/ovirt.py", line 622, in create
	self.build_entity(),
  File "x/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1376, in build_entity
  File "x/ansible/modules/cloud/ovirt/ovirt_vm.py", line 1293, in __get_template_with_version
AttributeError: 'NoneType' object has no attribute 'data_center'
```

##### EXPECTED RESULTS

You should obtain an explicit error which explains that cluster name was not found.

##### CODE ISSUE

In `__get_template_with_version` (file `ovirt_vm.py`, line 1293), the `cluster` variable is initialized with :
```python
cluster = search_by_name(clusters_service, self.param('cluster'))
```
And  just after, `cluster` is used to get it's `data_center` attribute without testing if it's value is `None` : 
```python
data_center = self._connection.follow_link(cluster.data_center)
```

A test shoud be added between : 
```python
cluster = search_by_name(clusters_service, self.param('cluster'))
if cluster is None:
     #  TODO  : GENERATE AN EXPLICIT ERROR HERE
data_center = self._connection.follow_link(cluster.data_center)

```

**Comment by mnecas** [comment]
@emesika
